###
GET http://localhost:5002/

###
GET http://localhost:5002/newsletters

###
GET http://localhost:3001/newsletters/1

###
POST http://localhost:5002/newsletters
Content-Type: application/json

{
    "issue": "11",
    "title": "test11",
    "tags": ["asasdf", "Asdf"]
}